### ISSUE TITLE
Wrapping a statement in a transaction exits early

### ISSUE THREAD

**Issue by AlexErrant** [vlcn-io/cr-sqlite#104]
Consider the following function, which is more or less a copy-paste of [this](https://github.com/vlcn-io/cr-sqlite/blob/34b710cc0fb83bc6f8d62f255baef3e9ebe5affe/js/sync-reference/whole-db/src/WholeDbReplicator.ts#L235-L275). The only major difference is that the transaction is commented out.

```ts
export const changesReceived = async (
  db: DB | DBAsync,
  changesets: readonly Changeset[]
) => {
  // await db.transaction(async () => { // uncomment to make fail
    let maxVersion = 0n;
    // console.log("inserting changesets in tx", changesets);
    const stmt = await db.prepare(
      'INSERT INTO crsql_changes ("table", "pk", "cid", "val", "version", "site_id") VALUES (?, ?, ?, ?, ?, ?)'
    );
    // TODO: may want to chunk
    try {
      // TODO: should we discard the changes altogether if they're less than the tracking version
      // we have for this peer?
      // that'd preclude resetting tho.
      for (const cs of changesets) {
        console.log("changeset", [cs[2], cs[3]])
        const v = BigInt(cs[4]);
        maxVersion = v > maxVersion ? v : maxVersion;
        // cannot use same statement in parallel
        await stmt.run(
          cs[0],
          cs[1],
          cs[2],
          cs[3],
          v,
          cs[5] // ? uuidParse(cs[5]) : 0
        );
      }
    } catch (e) {
      console.error(e);
      throw e;
    } finally {
      stmt.finalize();
    }
  // }); // uncomment to make fail
};
```

The above function works for the following code:

```ts
export const initSql = [
  `CREATE TABLE IF NOT EXISTS myTable (
    id BLOB PRIMARY KEY,
    a,
    b,
    c,
    d,
    e,
    f,
    g,
    h
);`,
  `SELECT crsql_as_crr('myTable');`,
]

const dbSource = aio.open()
dbSource.execMany(initSql)
dbSource.exec(
  `INSERT INTO myTable (id,a,b,c,d,e,f,g,h)
                  VALUES (?,?,?,?,?,?,?,?,?)`,
  [
    "A7A33CBF-65DD-4D36-B193-E64B9EC61EC7",
    "a value",
    "b value",
    "c value",
    "d value",
    "e value",
    "f value",
    "g value",
    "h value",
  ]
)

const changes: Changeset[] = await dbSource.execA<Changeset>(
  `SELECT "table", "pk", "cid", "val", "version", "site_id" FROM crsql_changes`
)

const dbTarget = aio.open()
dbTarget.execMany(initSql)

try {
  await changesReceived(dbTarget, changes)
} finally {
  console.log("closing db")
  dbTarget.close()
}
```

This is the output:

```
changeset [ 'a', "'a value'" ]
changeset [ 'b', "'b value'" ]
changeset [ 'c', "'c value'" ]
changeset [ 'd', "'d value'" ]
changeset [ 'e', "'e value'" ]
changeset [ 'f', "'f value'" ]
changeset [ 'g', "'g value'" ]
changeset [ 'h', "'h value'" ]
closing db
```

However, if I [uncomment the transaction](https://github.com/AlexErrant/node-playground/commit/1dbb31b909d4f0487fbb65d5e30e522655603a84), it fails with this output:

```
changeset [ 'a', "'a value'" ]
changeset [ 'b', "'b value'" ]
closing db
changeset [ 'c', "'c value'" ]
TypeError: The database connection is not open
```

It _seems_ like the transaction isn't being `await`'ed... but as far as I can tell ([in your code](https://github.com/vlcn-io/cr-sqlite/blob/34b710cc0fb83bc6f8d62f255baef3e9ebe5affe/js/browser/wa-crsqlite/src/wrapper.ts#L255-L266) and mine) it is. I've no idea why the `finally` is being called out of order. Any ideas?

Demo repo [here](https://github.com/AlexErrant/node-playground). This is on Node 16.13.0 because otherwise better-sqlite3 gets mad saying something like

> ...was compiled against a different Node.js version using NODE_MODULE_VERSION 108. This version of Node.js requires NODE_MODULE_VERSION 93

A clone/`pnpm i`/`pnpm run dev` should be enough to run the repo.

**Comment by AlexErrant** [comment]
[If I remove sqlite db](https://github.com/AlexErrant/node-playground/compare/master...remove_db), the transaction works as expected:

```ts
exec BEGIN
changeset [ 'a', "'a value'" ]
exec ["a","'a value'"]
changeset [ 'b', "'b value'" ]
exec ["b","'b value'"]
changeset [ 'c', "'c value'" ]
exec ["c","'c value'"]
changeset [ 'd', "'d value'" ]
exec ["d","'d value'"]
changeset [ 'e', "'e value'" ]
exec ["e","'e value'"]
changeset [ 'f', "'f value'" ]
exec ["f","'f value'"]
changeset [ 'g', "'g value'" ]
exec ["g","'g value'"]
changeset [ 'h', "'h value'" ]
exec ["h","'h value'"]
exec COMMIT
closing db
The end! yay
```

This makes me think the error isn't in the JavaScript.

**Comment by tantaman** [comment]
Thanks for the detailed repro. I Can take a look on Monday

**Comment by AlexErrant** [comment]
`@vlcn.io/crsqlite-allinone`'s `DB` is synchronous, so I can remove `await`. [When removing it from `stmt.run`](https://github.com/AlexErrant/node-playground/compare/master...notDBasync), it passes (with the transaction). I'm now _thoroughly_ confused... especially because [`await`ing a non-promise returns the value of the expression](https://stackoverflow.com/a/53113299). Perhaps this is just an artifact... either that or my OP was.

**Comment by tantaman** [comment]
Running your repro script --

```
> playground@1.0.0 dev /Users/tantaman/workspace/aerrant-104
> nodemon ./src/index.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node ./src/index.ts`
changeset [ 'a', "'a value'" ]
changeset [ 'b', "'b value'" ]
changeset [ 'c', "'c value'" ]
changeset [ 'd', "'d value'" ]
changeset [ 'e', "'e value'" ]
changeset [ 'f', "'f value'" ]
changeset [ 'g', "'g value'" ]
changeset [ 'h', "'h value'" ]
closing db
The end! yay
[nodemon] clean exit - waiting for changes before restart
```

I'll run it in a loop to see if it fails only sometimes and try downgrading to node16 to see if that reproduces the error.

Can you let me know if it still fails for you on node19?

**Comment by tantaman** [comment]
ah, was my mistake. I didn't uncomment the lines you told me to. Have it in a broken state now.

**Comment by tantaman** [comment]
The attached diff fixes it. Will merge it to main sometime today.

**Comment by tantaman** [comment]
it is probably best to write code that uses `better-sqlite3` in a synchronous way and I need to test the interactions with `better-sqlite3` if you try to pass it an async transaction. My guess is that it does not behave as intended and only works with synchronous transactions.

So I might actually end up throwing if you invoke `transact` on the `better-sqlite3` wrapper with an async callback. This breaks the ability to write something that works the same in the browser and in node but the alternative creates incorrect behavior.

I think the only way to get the same API in Node and the browser is to change everything from being promise based to being callback based. In synchronous environments the callback can be invoked immediately and not break any assumptions made by libraries like `better-sqlite3`. In async environments, the callback can be invoked when the promise completes.

**Comment by AlexErrant** [comment]
I found [a related issue](https://github.com/WiseLibs/better-sqlite3/issues/476) and this paragraph [in better-sqlite's docs](https://github.com/WiseLibs/better-sqlite3/blob/master/docs/api.md#caveats):

> Transaction functions do not work with async functions. Technically speaking, async functions always return after the first await, which means the transaction will already be committed before any async code executes. Also, because SQLite3 serializes all transactions, it's generally a very bad idea to keep a transaction open across event loop ticks anyways.
