### ISSUE TITLE
Please add .clang-format

### ISSUE THREAD

**Issue by sleepybishop** [vlcn-io/cr-sqlite#105]
`native/Makefile` has a `format` target via `clang-format`, it would be helpful to have the preferred `.clang-format` file in the repo to help contributors adhere to preferred style.

**Comment by AlexErrant** [comment]
Also wondering - do we have an opinion on [ESLint](https://eslint.org/) and/or [Prettier](https://prettier.io/)?

**Comment by tantaman** [comment]
@AlexErrant  - using Prettier. There's a prettierrc in the project root.

@sleepybishop - yeah, I've just been using vscode defaults 😬 but I'll figure out what those are and codify them in `clang-format`
