### ISSUE TITLE
How to install for WASM without vite?

### ISSUE THREAD

**Issue by iamwilhelm** [vlcn-io/cr-sqlite#182]
I'm using nextjs to try out the library, and I'm not using Vite. Hence, I tried to find a replacement for this line:

```
import wasmUrl from "@vlcn.io/crsqlite-wasm/crsqlite.wasm?url";
```

What I understand is that this is just a string saying where crsqlite.wasm is at. So I just added a soft link in `public` for the nextjs project.

```
cd public && ln -sf ../node_modules/@vlcn-io/crsqlite-wasm/dist/crsqlite.wasm
```

Then, I get this error:
```
wait  - compiling...
error - ./node_modules/@vlcn.io/crsqlite-wasm/dist/crsqlite.mjs:95:0
Module not found: Can't resolve 'wa-sqlite-async.wasm'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@vlcn.io/crsqlite-wasm/dist/index.js
./src/pages/_app.js
```

I can see that it's looking for `wa-sqlite-async.wasm`. I also soft linked it
```
cd public && ln -s ../node_modules/@vlcn.io/wa-sqlite/dist/wa-sqlite-async.wasm
```

But `crsqlite.mjs` doesn't seem to find it. Is there an official way to install it in nextjs without Vite?

**Comment by tantaman** [comment]
Hey. Is this happening in your dev environment, when you deploy to vercel
or both?

**Comment by iamwilhelm** [comment]
This is in the dev environment. I just fired up a new nextjs project using create-next-app, and then tried following your instructions on the docs. Lemme know if you need more info.

**Comment by tantaman** [comment]
The docs had an error but there is still another problem.

I think I see what it is -- should have a fix this evening.

**Comment by tantaman** [comment]
Thanks for reporting. Trying to fix this also uncovered some bugs related to React strict mode.

Didn't realize they had added a `strictMode` in React 18. The tldr is that it runs all effects twice (even effects that should only run on component mount) which causes subscriptions to break.

**Comment by tantaman** [comment]
ok, got everything working locally. Going to publish some release candidates to npm that you can try out.

**Comment by tantaman** [comment]
@iamwilhelm  - mind giving this a spin?

https://github.com/tantaman/nextjs-starter

The main change is this webpack config in `next.config.js`:

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  webpack: (config, { isServer }) => {
    config.module.rules.push({
      test: /\.wasm/,
      type: 'asset/resource'
    });
    return config;
  }
}

module.exports = nextConfig
```

and the other is pointing to some release candidates for cr-sqlite in `package.json`

```
"@vlcn.io/crsqlite-wasm": "^0.9.2-next.1",
"@vlcn.io/react": "^0.9.2-next.1",
"@vlcn.io/rx-tbl": "^0.8.2-next.1",
```

`index.tsx` has some basic usage of the DB. It isn't calling out to a sync server -- I'm in the process of creating a community sync server that people can use as a default until they're ready to host their own.

**Comment by iamwilhelm** [comment]
I cloned it and it seems like it worked! I'll adapt it to my own project. Thanks!

**Comment by wovalle** [comment]
Hey @tantaman I triead to access that repo but is no longer available. Do you have any other examples using either remix or next? thanks!
