### ISSUE TITLE
Invalid error message

### ISSUE THREAD

**Issue by Azarattum** [vlcn-io/cr-sqlite#188]
I got an error saying `Integer part should not end with 0` and was super confused. Not only that it should be okay for the integer part to end with zero, but also non of my inputs had it ending with zero. After digging through some code I've realised that the error meant to say `Fractional part should not end with 0` which makes sense algorithmically. The code just above is checking the **fractional** part, not the integer.

https://github.com/vlcn-io/cr-sqlite/blob/35c3006f342b847d51bd0c5083c3988089131d1f/core/rs/fractindex-core/src/fractindex.rs#L178

So, I believe this is a typo.

**Comment by tantaman** [comment]
Thanks. Was there an actual bug, btw?

**Comment by Azarattum** [comment]
Just the typo. The bug was on my end when I’ve generated a bunch of order indexes manually.
