### ISSUE TITLE
decode failure Invalid DataView length

### ISSUE THREAD

**Issue by iansinnott** [vlcn-io/cr-sqlite#189]
I'm getting the following from the logs of vlcn-websocket after a client connects.

```
error: decode failure Invalid DataView length 8 {"event":"Connection.#onMsg.decodeFailure","timestamp":"2023-04-17T16:18:29.201Z"}
```

Any ideas on what might be causing this? I was able to run the todo example locally, ensured I'm on the same versions as the live-examples codebase.

**Comment by iansinnott** [comment]
It did not. Fresh clone seems to work fine, so it's likely something specific to my project. 

Any thoughts on what might be influencing the messages sent to the websocket server? I iterated on the db for a while before trying to hook up syncing, so is it possible something related to the schema is causing problems?

<details>
<summary>Chat schema.sql</summary>

```sql
CREATE TABLE
  if NOT EXISTS "thread" (
    "id" VARCHAR(255) PRIMARY KEY,
    "title" VARCHAR(255),
    "created_at" TIMESTAMMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

SELECT
  crsql_as_crr ('thread');

CREATE TABLE
  if NOT EXISTS "message" (
    "id" VARCHAR(255) PRIMARY KEY,
    "cancelled" BOOLEAN DEFAULT FALSE,
    "content" TEXT,
    "thread_id" VARCHAR(255),
    "created_at" TIMESTAMMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

SELECT
  crsql_as_crr ('message');

CREATE INDEX if NOT EXISTS messagethreadidx ON "message" ("thread_id");

CREATE TABLE
  if NOT EXISTS "preferences" ("key" VARCHAR(255) PRIMARY KEY, "value" TEXT);

SELECT
  crsql_as_crr ('preferences');
```

</details>

If there's nothing obvious here then I can put together a repro, or perhaps new format will resolve the issue.

**Comment by tantaman** [comment]
The contents of the db shouldn’t impact the serialization format at all so
this sounds like a bug. Will take a look in the morning.

**Comment by tantaman** [comment]
Btw, do you have a repro? Is it just using that schema and then trying to write that creates issues?

**Comment by tantaman** [comment]
closing but feel free to re-open if you have a repro.
