### ISSUE TITLE
Support more queries for `crsql_changes`

### ISSUE THREAD

**Issue by jeromegn** [vlcn-io/cr-sqlite#195]
For our use case, we need to be able to query ranges of changes by `db_version` and `site_id`.

Example:

```
SELECT ... FROM crsql_changes WHERE site_id = ? AND db_version >= ? AND db_version <= ?;
```

However, we either get an error, no rows returned or the wrong rows are returned with various combinations of conditionals.

**Comment by tantaman** [comment]
Looks to be working as expected in this branch: https://github.com/vlcn-io/cr-sqlite/pull/199

Still to do:
- update the docs
- add property based test for different combinations of filters and operations

**Comment by tantaman** [comment]
Packages will be available for JS users as soon as this is resolved:

> We continue to see extremely delayed package publishes and continue to investigate.
- https://status.npmjs.org/
