### ISSUE TITLE
`crsql_rows_impacted` always returns `0`

### ISSUE THREAD

**Issue by jeromegn** [vlcn-io/cr-sqlite#241]
Probably best explained with a small example:

```
sqlite> CREATE TABLE foo (id integer primary key, b integer);
sqlite> .mode column
sqlite> select crsql_as_crr('foo');
crsql_as_crr('foo')
-------------------

sqlite> begin;
sqlite> insert into foo values (2, 3);
sqlite> insert into foo values (3, 4);
sqlite> insert into foo values (4, 5);
sqlite> select crsql_rows_impacted();
crsql_rows_impacted()
---------------------
0
sqlite> commit;
sqlite> select *, seq from crsql_changes;
table  pk  cid  val  col_version  db_version  site_id  seq
-----  --  ---  ---  -----------  ----------  -------  ---
foo    2   b    3    1            1                    0
foo    3   b    4    1            1                    1
foo    4   b    5    1            1                    2
```

Important part is before committing I check `crsql_rows_impacted` and got `0`:

```
sqlite> select crsql_rows_impacted();
crsql_rows_impacted()
---------------------
0
```

I expected `3` to be returned here.

**Comment by tantaman** [comment]
Looking back through my tests --

https://github.com/vlcn-io/cr-sqlite/blob/main/core/src/rows-impacted.test.c

Looks like `rows_impacted` only counted when inserting against the `crsql_changes` virtual table.

Does it need to expand to covering all insertions? My recollection is a bit hazy but I thought we needed the count only when merging changes from other peers.

**Comment by jeromegn** [comment]
Huh. You’re right haha. My bad :(
