### ISSUE TITLE
Create After Delete Diverges

### ISSUE THREAD

**Issue by JasonPunyon** [vlcn-io/cr-sqlite#271]
Hello! 👋🏻

I'm running against version 0.13 and I have a test script I'm running that looks like this...

```{csharp}
void CreateAfterDelete() => Test("Create After Delete",
                                 WithDatabase(out var db1), WithDatabase(out var db2), // Two Databases
                                 Create(db1, 1, "One", "One"),                         // Create record Id = 1 at DB1
                                 Sync(db1, db2),                                       // Sync
                                 Delete(db1, 1),                                       // Delete record Id = 1 at DB1
                                 Sync(db1, db2),                                       // Sync
                                 Create(db1, 1, "New", "New"),                         // Create Record Id = 1 at DB1
                                 Sync(db1, db2),                                       // Sync
                                 Reconcile(db1, db2));                                 // Reconciliation Fails. (DB1 has the record, DB2 does not)
``` 

It:

1. Creates a record Id = 1 @ DB1
2. Syncs
3. Deletes the record Id = 1 @ DB1
4. Syncs
5. Creates a new record Id = 1 @ DB1
6. Syncs

At this point I'd expect both DB1 and DB2 to have the new record, but only DB1 contains the new record.

Is that the expected behavior? If not, would you like a full repro? I can get you one, but I didn't want to go to the trouble before confirming the expected behavior.

Thanks so much for your help! This is a really cool project!

**Comment by tantaman** [comment]
Cr-sqlite currently doesn't support re-inserting something that was previously deleted. It'll be implemented soon (next week or two) as it is one the most requested features. For reference-- issue #71

**Comment by JasonPunyon** [comment]
(I shoulda searched 😅)

Rad! 🤘🏻 Thanks again!
