### ISSUE TITLE
Build for arm64

### ISSUE THREAD

**Issue by alanjhughes** [vlcn-io/cr-sqlite#275]
Is it possible to build for arm64 to use the extension on iOS?

**Comment by tantaman** [comment]
There is an arm build under releases. I'm told, however, that iOS doesn't allow dynamic loading of SQLite extensions and it'd instead have to be compiled directly into the SQLite library.

If you're going down the iOS route, lmk if this is in fact the case and we can figure something out.

**Comment by alanjhughes** [comment]
Sorry about opening an issue to get in contact. I've reached out on twitter if that works better?

**Comment by louwers** [comment]
SQLite tries to load `.dylib` on iOS, but the distributed XCFramework has no extension.
