### ISSUE TITLE
cr-sqlite is now in the SQLite package registry

### ISSUE THREAD

**Issue by nalgeon** [vlcn-io/cr-sqlite#296]
Hi! I've just added `vlcn-io/cr-sqlite` to the [package registry](https://sqlpkg.org/). It's now available on the website and via the CLI [package manager](https://github.com/nalgeon/sqlpkg-cli#readme).

No action is required on your part, just a quick heads up.

Thank you for this great extension!

P.S. It would really help though if you could remove the "rename" step, which is not obvious to people and unfortunately not supported by the package manager:

> The entrypoint to the loadable extension is sqlite3_crsqlite_init, so you'll either need to provide that to load_extension or **rename your binary** to crsqlite.[dylib/dll/so].

Extension authors often publish .zip or .tar.gz archives with an extension binary inside, like this:

```
crsqlite-darwin-x86_64.zip
└─ crsqlite.dylib

crsqlite-darwin-aarch64.zip
└─ crsqlite.dylib

crsqlite-linux-x86_64.zip
└─ crsqlite.so

crsqlite-linux-aarch64.zip
└─ crsqlite.so

crsqlite-windows-x86_64.zip
└─ crsqlite.dll
```

This way there is no need to rename the binary, and the extension works right after unpacking.

**Comment by tantaman** [comment]
Thanks @nalgeon.

I'll update the [publish](https://github.com/vlcn-io/cr-sqlite/blob/main/.github/workflows/publish.yaml) workflow to fix that.

**Comment by nalgeon** [comment]
Thanks for implementing this change! Looking forward to the next release with zipped assets.
