### ISSUE TITLE
move crsql_createCrr to Rust

### ISSUE THREAD

**Issue by tantaman** [vlcn-io/cr-sqlite#325]
beginner task to conver `createCrr` to Rust

**Comment by Azarattum** [comment]
@tantaman, I've started working on this. Currently moved [isTableCompatible](https://github.com/Azarattum/CRSqlite/commit/390fed5760e3654a39ff89da21bc7d7481f98a5b),  [getTableInfo and freeTableInfo](https://github.com/Azarattum/CRSqlite/commit/d1aaae5864fe75239b10e3a31ff3be629c8c5e5d) to Rust. I'll fire a PR once everything is ready.

**Comment by tantaman** [comment]
Awesome. I'll be able to review this pretty much immediately. The typed-sql stuff is still on the back burner for me until we have text CRDTs & a native reactivity extension for SQLite.
