### ISSUE TITLE
Support `PRAGMA journal_mode=WAL;`?

### ISSUE THREAD

**Issue by AlexErrant** [vlcn-io/cr-sqlite#379]
Using the latest https://github.com/vlcn-io/live-examples as my playground, I added

```ts
  console.log(await db.execO("PRAGMA journal_mode=memory;"));
```

which correctly yields `[
    {
        "journal_mode": "memory"
    }
]`

However,

```ts
console.log(await db.execO("PRAGMA journal_mode=WAL;"));
```

yields `[
    {
        "journal_mode": "delete"
    }
]`

Notably, `PRAGMA journal_mode=WAL;` works on https://rhashimoto.github.io/wa-sqlite/demo/

If it matters, I'm just trying WAL mode because it apparently may improve perf.

**Comment by rhashimoto** [comment]
> Notably, PRAGMA journal_mode=WAL; works on https://rhashimoto.github.io/wa-sqlite/demo/

It works in the wa-sqlite demo if you use the default in-memory VFS, but not with any other VFS. WAL requires a shared memory implementation in the VFS to work, which no wa-sqlite example VFS has.

It's possible to implement the shared memory calls (I think) but (1) I don't know if sharing via SharedArrayBuffer or message passing will be particularly performant, and (2) no browser persistence API currently allows simultaneous reads and writes that maximize WAL benefits (though there's a [proposal](https://github.com/w3ctag/design-reviews/issues/845) to change this for OPFS).

See also [this SQLite forum thread](https://sqlite.org/forum/info/57786a5c62bd9bad).

**Comment by AlexErrant** [comment]
Ulgh I just kinda ignored `Unix / Standard` because well... why would I be on anything different... and of course that would indicate the root problem.

Thanks for the info dump! I look forward to OPFS becoming tenable for wa-sqlite someday.

**Comment by rhashimoto** [comment]
> I look forward to OPFS becoming tenable for wa-sqlite someday.

wa-sqlite does have two example OPFS VFS's, OriginPrivateFileSystemVFS and AccessHandlePoolVFS. They are both in the [demo](https://rhashimoto.github.io/wa-sqlite/demo/) and [benchmarks](https://rhashimoto.github.io/wa-sqlite/demo/benchmarks.html) pages. If you're after performance, AccessHandlePoolVFS is the [fastest](https://github.com/rhashimoto/wa-sqlite/discussions/86) wa-sqlite VFS on those benchmarks except for write transaction overhead.

**Comment by tantaman** [comment]
@AlexErrant  -

I've been brainstorming with the ElectricSQL folks (here: https://discord.com/channels/933657521581858818/1157258041318703114) on how to improve perf for reactive/live queries.

One idea is that live queries can be optimistically updated synchronously without round-tripping to SQLite. Obviously there's tons of gotchas here, a few being:

- Triggers won't have run before making the optimistic update to live results
- Constraint checks won't have run
- The transaction could fail in SQLite, requiring optimistic updates to be rolled back

Another idea is to compile an extension into SQLite which knows of all currently active live queries. On write, we'll update all live queries within the WASM module itself without having to make round-trips from WASM to JS for each live query.

The second idea is the most practical, doesn't come with any gotchas and likely will get us most of what we need.

----

**Comment by tantaman** [comment]
@AlexErrant - practically speaking though, what sort of perf issues are you hitting? Maybe there's some simple things we can do now.
