### ISSUE TITLE
no such function: crsql_internal_sync_bit

### ISSUE THREAD

**Issue by sinkingsugar** [vlcn-io/cr-sqlite#423]
Hi, thank you for this library 👍 , we are experimenting using it in a soon to be announced game creation system.
So far so good. We use a slight older version cos current main branch gives an out of memory error on iOS, but that is not the issue here.

Opening a slightly older DB (still version 15000 though), I'm getting sporadically such:
`no such function: crsql_internal_sync_bit` when doing Update ops.

Any idea on what is potentially going on would be appreciated?

Thank you 🙏 

Edit: The extension is loaded as dll, successfully and many other queries already happened fine. Also we are heavily using threads but in a controlled manner.

**Comment by sinkingsugar** [comment]
Small update:
Shuffling things around fixed it. By shuffling I mean every query is still running on different threads on a pool, but at a different pace. It's weird because there is still they same transaction mutex on the db connection (so there is only 1 write at any time)

**Comment by tantaman** [comment]
This error means that the extension wasn't loaded on the given connection. Is it possible that new connections are being used before loading the extension in your setup?

**Comment by sinkingsugar** [comment]
> This error means that the extension wasn't loaded on the given connection. Is it possible that new connections are being used before loading the extension in your setup?

Thank you! Highly unlikely to be honest, that's why I'm very puzzled. I will give it another pass though.

**Comment by sinkingsugar** [comment]
I found a possible cause indeed. Closing this for now! 
I will try to repro the iOS issue soon as well.

**Comment by tantaman** [comment]
I found an issue that impacted WASM and could have caused this. I'll be publishing the fix in 0.16.3

Did you ever track down the problem on your end?
