### ISSUE TITLE
drop history on delete

### ISSUE THREAD

**Issue by tantaman** [vlcn-io/cr-sqlite#59]
in our current "delete wins" configuration we can drop all history for a row on delete.

**Comment by ivertom** [comment]
Wouldn't delete history be needed to differentiate between a row being deleted vs never having existed?

**Comment by tantaman** [comment]
My thinking was that if "delete wins" you can just keep the delete record for the row and remove all prior (update and create) records?

**Comment by tantaman** [comment]
Since last we talked I did move to a "delete wins" model. 

My idea there was that if someone wanted something different they could add a column "is_delete" at the application level and track deletes in app.

Curious for your thoughts.

**Comment by ivertom** [comment]
1. Yeah, that could be a way to remove redundant metadata.

2. I do agree a delete should win over an update. This is in many ways similar to how it was done in the original crr approach where we used a causal length field per row, so a delete would beat out an update (but a delete then re-insert would beat that again... and so on).

**Comment by ivertom** [comment]
Could go for a causal length record for each row (instead of a delete
record)? Should be a pretty quick fix to cover this, unless there's
something I'm not seeing?

ons. 23. nov. 2022, 15:03 skrev Matt ***@***.***>:

**Comment by tantaman** [comment]
#229 does this

And #71 will implement causal length for delete / create records.
