### ISSUE TITLE
Overflow when column is INT (or BIGINT)

### ISSUE THREAD

**Issue by AlexErrant** [vlcn-io/cr-sqlite#85]
The following code

```ts
const memDb = await sqlite.open(":memory:")
await memDb.execMany([
  `CREATE TABLE IF NOT EXISTS todo_list1 ("name" primary key, "creation_time" BIGINT);`,
  `CREATE TABLE IF NOT EXISTS todo_list2 ("name" primary key, "creation_time");`,
])

await memDb.exec(`INSERT OR IGNORE INTO todo_list1 VALUES ('groceries', ?)`, [
  Date.now(),
])
await memDb.exec(`INSERT OR IGNORE INTO todo_list2 VALUES ('groceries', ?)`, [
  Date.now(),
])
const r1 = await memDb.execO(`SELECT * FROM todo_list1`)
const r2 = await memDb.execO(`SELECT * FROM todo_list2`)
console.log("r1", r1[0].creation_time)
console.log("r2", r2[0].creation_time)
```

yields this output:

```
r1 -721617812
r2 1670020660333
```

I'm new to SQLite. Is this expected behavior? It doesn't overflow in DBBrowser, though this query isn't parameterized:

![image](https://user-images.githubusercontent.com/109672176/205401825-3f3dfa17-dce0-464a-b95a-0579e4e297e2.png)

**Comment by tantaman** [comment]
Thats not expected. I’ll dig into the wasm build since it’s most likely a
problem with the wasm port.

**Comment by tantaman** [comment]
The SQLite wasm build I’m using currently doesn’t support bigint but
date.now shouldn’t be overflowing a js number.

**Comment by AlexErrant** [comment]
FYI I'm just exploring - if this is something that would be fixed with the eventual move to "Official Sqlite WASM" (I think we're on wa-sqlite) I'm cool with waiting.

**Comment by tantaman** [comment]
Tbh I’m pretty disappointed in the SQLite wasm builds that are available
and might need to pivot to investing heavily into getting one of them
production ready.

**Comment by tantaman** [comment]
But yes this should be solved with the official build

**Comment by tantaman** [comment]
will be fixed by #43

**Comment by tantaman** [comment]
Still need to do a bunch more testing but this might do the trick -- https://github.com/vlcn-io/wa-sqlite/tree/bigint2

**Comment by tantaman** [comment]
tested it some more and everything seems in order except virtual tables that are defined in javascript.

Given a JS defined VTab is highly unlikely to happen before the official sqlite build is in a good state I think I'll merge  https://github.com/vlcn-io/wa-sqlite/pull/2 in order to unblock bigint support.

this'll also let me remove a number of hacks in my networking layer that case from text to int64 and back again.

**Comment by tantaman** [comment]
Looks like the author of wa-sqlite is going to take a stab at fixing bigint support.

I'm going to hold off on merging my changes for a bit to see what he comes up with.

**Comment by rhashimoto** [comment]
@tantaman I _am_ going to work on 64-bit integer support but don't expect it right away; I was just posting notes on scoping the effort. All I can tell you is I'm not coding it right now but I'll be surprised if I don't get to it this month.

I'll try to update the wa-sqlite bug if/when the schedule firms up.
